pipeline:
  java8:
    group: build
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=/drone/.gradle
    commands:
      - ./gradlew test
  discord:
    image: appleboy/drone-discord
    secrets: [ discord_webhook_id, discord_webhook_token ]
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
    when:
      status: [ success, failure ]
