pipeline:
  discord:
    image: appleboy/drone-discord
    secrets: [ discord_webhook_id, discord_webhook_token ]
    message: "Testing from drone image"
  java8:
    group: build
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=/drone/.gradle
    commands:
      - ./gradlew test
