---
pipeline:
  java8:
    group: build
    image: gradle:4.8.1-jdk8
    pull: true
    environment:
      - GRADLE_USER_HOME=/drone/.gradle
    commands:
      - mkdir /drone/.gradle
      - chown -R gradle:gradle /drone/.gradle
      - gradle test -s

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
    when:
      status: [ success, failure ]
